name: cmake --workflow --preset test:*
on:
  push:
    # branches: ["main"]
    branches: ["jcbhmr-patch-1"] # FIXME
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/cmake-workflow-preset-test.yml"
  pull_request:
    paths-ignore:
      - docs/**
      - examples/**
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/cmake-workflow-preset-test.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cmake-workflow-preset-test:
    strategy:
      fail-fast: false
      matrix:
        # https://gist.github.com/jcbhmr/ff6abde60ae32de0e33f93ed7445e78e
        target: [
          "aarch64-linux-gnu",
          "aarch64-linux-musl",
          "aarch64-windows-gnu",
          "aarch64-macos-none",
          "arm-linux-gnueabi",
          "arm-linux-gnueabihf",
          "arm-linux-musleabi",
          "arm-linux-musleabihf",
          "thumb-linux-musleabi",
          "thumb-linux-musleabihf",
          "x86-linux-gnu",
          "x86-linux-musl",
          "x86-windows-gnu",
          "mips64el-linux-musl",
          "mips64-linux-musl",
          "mipsel-linux-gnueabi",
          "mipsel-linux-gnueabihf",
          "mipsel-linux-musl",
          "mips-linux-gnueabi",
          "mips-linux-gnueabihf",
          "mips-linux-musl",
          "powerpc64le-linux-gnu",
          "powerpc64le-linux-musl",
          "powerpc64-linux-gnu",
          "powerpc64-linux-musl",
          "powerpc-linux-musl",
          "riscv64-linux-musl",
          "wasm32-wasi-musl",
          "x86_64-linux-gnu",
          "x86_64-linux-gnux32",
          "x86_64-linux-musl",
          "x86_64-windows-gnu",
          "x86_64-macos-none"
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: jwlawson/actions-setup-cmake@v2
      - uses: goto-bus-stop/setup-zig@v2
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('**') }}
          path: build/${{ matrix.target }}
      - run: cmake --workflow --preset "build:$TARGET"
        env:
          TARGET: ${{ matrix.target }}
      - run: cmake --workflow --preset "test:$TARGET"
        env:
          TARGET: ${{ matrix.target }}
